name: Run Hello Action
on:
  push:
    tags:
      - 'v*'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Get issues and push body
        uses: actions/github-script@0.9.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.VERSION }}
          script: |
            console.log(version);
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            }).then(response => {
              response.data.forEach(issue => {
                console.log(issue)
              });
            });
