name: Run Hello Action
on:
  push:
    tags:
      - 'hoge'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Get issues and push body
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload);
            const tag_name = context.payload.ref.replace('refs\/tags\/', '');

            console.log('tag_name:' + tag_name);
            const res_release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag_name
            });
            if (res_release.status != 200) {
              console.log('Get a release by tag name fail');
              exit;
            }
            console.log(res_release);
            const rel_id = res_release.data.id;

            const res_issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            if (res_issues.status != 200) {
              console.log('List repository issues fail');
              exit;
            }

            let release_body = '';
            res_issues.data.forEach(issue => {
              try {
                if (issue.milestone.title == tag_name) {
                  release_body += '- ';
                  release_body += issue.title + ' ';
                  release_body += '#' + issue.number;
                  release_body += '\n';
                }
              } catch(error) {
                // マイルストーンなしはそのまま継続
              }
            });
            console.log(release_body);

            const res_update = await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: rel_id,
              body: release_body
            });
            if (res_update.status != 200) {
              console.log('Edit a release fail');
              exit;
            }
            console.log(res_update);
