name: Run Hello Action
on:
  push:
    tags:
      - 'v*'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Get issues and push body
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload.ref.replace('refs\/tags\/', ''));
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            }).then(response => {
              response.data.forEach(issue => {
                console.log(issue)
              });
            });
