name: Create release note
on:
  push:
    branches:
      - master

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: mougenko/create-release-note@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
